sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    package:
      - chefdk

services: docker


before_script:
  -eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embeded/bin/chef --version

script: /opt/chefdk/embeded/bin/kitchen verify

matrix:
  include:
    - before_script:
      - eval "$(/opt/chefdk/bin/chef shell-init bash)"
      - /opt/chefdk/embeded/bin/chef --version
      - /opt/chefdk/embeded/bin/cookstyle --version
    - script:
      - /opt/chefdk/bin/chef exec cookstyle
