---
driver:
  name: dokken
  chef_version: latest
  privileged: true #because Docker and SystemD/Upstart


transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: centos73
    driver:
      image: centos:7.3.1611
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts net-tools


suites:
  - name: default
    run_list:
      - recipe[motd_attributes::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
